# Ansible_group_priority: highest number last 
# Playbook dir inventory overrides default inventory /etc/ansible
# Groupvars has to be in same dir as inventory
# Inventory in Dir ASCII order - best practice number files 01, 02, 03, etc
#   Pass -i staging -i production to run the playbook with myvar = 2.
#   Pass -i production -i staging to run the playbook with myvar = 1.
---
all:
  children:
    control_plane:
      hosts:
        3.15.102.110:
    worker:
      hosts:
        3.18.182.12:
    k8s:
      children:
        control_plane:
        worker:
