apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: db-one
  name: db-one
  namespace: prod-a
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: LFtr@in
    image: mariadb
    name: db-one
    ports:
    - containerPort: 3306
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always

