apiVersion: v1
kind: Pod
metadata:
  name: securityreview
spec:
  securityContext:
    runAsUser: 101
  containers:
  - name:  webguy
    image: nginx
    securityContext:
      runAsUser: 101
      allowPrivilegeEscalation: false
