apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  ## try to restart the job up till this timer if over fail
  ## and wait till next run
  ## Controller checks every 10s so anything under 10s might not work
  ## startingDeadlineSeconds: 100 (seconds)
 
  # concurrencyPolicy: [Allow, Forbid, Replace]

  # if a suspended job is missed without starting deadline
  # it will auto refire when unsuspended
  # suspend: true || false

  # Number to keep
  # successfulJobHistoryLimit: default 3
  # failedJobHistoryLimit: default 1

  # timeZone: #Beta in v1.25
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure